### ISSUE TITLE
静的な変換テーブルは作成可能ですか？

### ISSUE THREAD

**Issue by tomoemon** [google/horenso#1]
Google 日本語入力のローマ字テーブルにこの入力方式の変換テーブルを入れて試してみたいと思ったのですが、`hrs` スクリプトは実行時に動的に変換テーブルを生成して保持しているように見えます。（ひらがなの変換テーブルを使ってカタカナのマッピングを自動生成する等）

この入力方式は原理的に静的な変換テーブルを作成することができないのでしょうか？

**Comment by matvore** [comment]
このスクリプトを使ってみてもらえますか？CodeMap.pm内のコード生成ロジックを使って全コードをプリントアウトします。ほー連想ダイレクトリーにコピーして実行してください。

https://gist.github.com/matvore/f0fe86c2e6774c415b4f

お役に立てばレポジトリーに保存します。

**Comment by tomoemon** [comment]
ありがとうございます！試してみます！

**Comment by tomoemon** [comment]
出力できましたが、17000パターンもあるんですね！
そのままだと Google 日本語入力ローマ字テーブルに入れられない（MAX10000パターン）ので、中国語繁体字や旧字等を省ければと思うのですが、そういったことは可能でしょうか？

ぱっと見た感じ、そういった文字は大文字のアルファベットを含むパターンに割当てられているように見えますが、雑にそれを全部消してしまって良いものかどうか教えていただけるとありがたいです。

**Comment by matvore** [comment]
そこまで異体字を導入していないので、それらを保持しても良いです。

が、お分かりだと思うけれどｈｒｓはCAPSLOCKがオンでも普通に漢字が入力できます（カタカナ交じり漢字を入力するため）これら小文字＋大文字が反転しているパターンを消せば~10500個が残るけど、そのほかに使えなさそうパターンも消せばパターン数はぎりぎり制限内です。（https://github.com/google/horenso/commit/0f3d86444abcff9c5d9a95c44ab96baa61179399 参照）

更新したexpand_codesスクリプトを別ブランチとしてアップしました。pullしてみてください。

```
$ git pull https://github.com/google/horenso.git expand_codes:expand_codes
$ git checkout expand_codes
$ ./expand_codes | wc -l
9878
```

**Comment by tomoemon** [comment]
ありがとうございます。
9878件のエントリを登録できることを確認しました。

**Comment by matvore** [comment]
@tomoemon さん、expand_codesの出力した内容はそのままググ日で開いて使えましたか？もしそうでしたら、[Releasesページ](https://github.com/google/horenso/releases)にアップします。

もしテーブルで修正が必要でしたら、expand_codesを更新しときます。

**Comment by tomoemon** [comment]
結果から報告すると、正しく登録できて入力も問題ありませんでした。

ただ、単純にローマ字テーブルだけを入れ替える形で登録してみたたところ、「入力」に大文字のアルファベットが入っていると入力できないようでした。
（先週登録した際は、このようなアラートは出ていなかったと思うのですが、先ほど試してみたところアラートが出ました）
![google_ime_alert](https://cloud.githubusercontent.com/assets/1381362/13483702/449b35ba-e13a-11e5-9aaf-b2556274a14f.png)
実際に `1R7 > ッリャ` を試そうとすると `１R７` と `R` の部分だけが半角文字として出力（ローマ字テーブルを介さずに確定）されてしまいました。

そこで、下記画像の設定にある通り「Google 日本語入力のプロパティ→入力補助→シフトキーでの入力切替」を「オフ」（デフォルト：英数字）にしたところ、大文字アルファベットが含まれているパターンについても入力できました。
![google_ime_setting](https://cloud.githubusercontent.com/assets/1381362/13483784/ed869778-e13a-11e5-9d8a-6db2c216962e.png)

アラートのメーセージを読む分には自動的にこの設定もオフになるように見えますが、実際はシフトキーでの入力切替は変わっていなかったので、手動で設定を変える必要がありそうです。
このファイルをリリースするのであれば、その説明も一言あった方が良いかもしれません。

**Comment by matvore** [comment]
@tomoemon さん、丁寧な説明を有難うご座います！ググ日を使うのに役に立つと思うので、Wikiにコピペしたいのですが、そうするには、[貢献者の同意書 (CLA)](https://developers.google.com/open-source/cla/individual?csw=1)の同意を頂かないといけません。お手数ですが、Webで同意を宣言して頂けますでしょうか？(Web FormにGitHub名の記入を忘れずにですね）

同意しましたら、一言で「やりました」と返事をお願いします。こちらで確認して作業を進めます。

もしご同意を頂けなければ、自分でちっぽけな説明はできますが、それですむと勿体無いと思いますね。

**Comment by matvore** [comment]
言い忘れましたが、 https://github.com/google/horenso/releases にググ日用の変換テーブルをアップしました。

**Comment by tomoemon** [comment]
@matvore CLA 同意しました！

**Comment by matvore** [comment]
ありがとうございます！[Wiki](https://github.com/google/horenso/wiki/%E3%82%B0%E3%83%BC%E3%82%B0%E3%83%AB%E6%97%A5%E6%9C%AC%E8%AA%9E%E5%85%A5%E5%8A%9B%E3%81%AE%E3%83%AD%E3%83%BC%E3%83%9E%E5%AD%97%E3%83%86%E3%83%BC%E3%83%96%E3%83%AB%E3%82%92%E4%BD%BF%E3%81%86%E3%81%AB%E3%81%AF) にコピーさせて頂きました。Releaseページにもリンクを入れておきました。
