### ISSUE TITLE
漢直Win用の変換テーブルを作成

### ISSUE THREAD

**Issue by matvore** [google/horenso#2]
漢直Winを少しだけ触ってみたけれど、シフト打鍵と我々が必要とする全キーをサポートしているのは良いですね。

気になるのは一時に複数字の変換ができるでしょうか（例：3ru -> ある）？それに、`t.tbl`や`tut.tbl`がShift JIS形式であることから、JISにない字を取り除く必要があるかも知れません。

**Comment by seigo-masumura** [comment]
漢直Win 1.28で試してみたところ、
1. 複数文字の入力自体はできる（ただし『漢直窓』では先頭の1字だけ、『漢索窓』では1字単位の打ち方が表示される）
2. ShiftJIS以外で書かれたテーブルファイルを"kanchoku.ini"のtableFileに指定すると起動時にエラーが出る

という結果になりました。

それから、3打鍵以上になるとテーブルの階層が深くなって扱いにくくなるので、1.28で導入された“矢印定義”を使って、

`-2>-13>-16>"ある"`

のように書いた方が簡単だろうと思います。

**Comment by matvore** [comment]
一応 問題の行を残したテーブルをアップします。1347行目が間違っているというエラーが出るけれど、行番号が違う気がします。

[hrs.tbl.txt](https://github.com/google/horenso/files/150243/hrs.tbl.txt)

**Comment by matvore** [comment]
変換テーブルを修正して只今使ってます！生成に使った`expand_codes`スクリプトを`master`にマージしました。

ダウンロードして使ってみてください：
[hrs.tbl.txt](https://github.com/google/horenso/files/150440/hrs.tbl.txt)

因みに、問題は《 \ 》をエスケープし忘れました。

Linuxでコードテーブルを生成するには：

```
./expand_codes kanchoku_win > hrs.tbl
```

を実行します。

expand_codesの開発中に他のバグも発覚しましたが、《：》の代わりに《＇》が幾つかのコードに入っていました。日本語配列だけのバグなので普段US配列を使っている私は気が付きませんでした。ついでにそのバグも直しておきました。

残念ながら、漢直WinはCAPS LOCKを無視するらしいので、取りあえずカタカナを入力する時はシフトを長押ししなければなりません。

**Comment by seigo-masumura** [comment]
おおっ、ありがとうございます。さっそく試してみます！

**Comment by seigo-masumura** [comment]
Caps Lockがきかないのがざんねんだったので、`漢直Win`のドキュメントの`特殊定義の一覧`のなかにある`かたかなモードの切り替え`というのをつかって、

> -20>-20>@K

というぎょうをついかしてみました。（`a`の2だけんでトグルします）
シフトしたままうつよりかんたんになりました。

このあと、`kanchoku.ini`の

> ;; Unicode対応テスト
> ;; - テーブルファイルでの定義が "U+????" (U+0000～U+3FFF) の場合 Unicode 一文字と解釈する
> ;; - SJIS全角文字、半角かなについても PostMessageW を用いて Unicode で送出する
> outputUnicode=1

というのをためしてみようとおもいます。

**Comment by seigo-masumura** [comment]
`kanchoku.ini`で`outputUnicode=1`として、`hrs.tbl.txt`の`"\x{0000}"`～`"\x{3fff}"`にマッチする部分を`"U+0000"`～`"U+3fff"`に置換してみたら、〘〙〖〗などが2ストローク入力できるようになりました。
`"U+4000"`以上の文字も入力できればよかったのですが、テスト用ということなので仕方ないですね。

**Comment by matvore** [comment]
@seigo-masumura さん：なるほど。カタカナモードがあったんですね。ａａで切替できるようにさせて頂きました。ご提示のお陰で簡単にテーブル作成ができまして有難うご座います。

`U+4000`以上を認識しないという点ですが、漢直Ｗｉｎの方に頼めば直してくださるかも知れません。Windowsの開発環境が手元にないので、こちらで更新するのは難しいのですが。

**Comment by tomoemon** [comment]
動作に影響はないと思いますが、リリースされている漢直 Win テーブル定義ファイルに \n と \r\n の改行コード（18行、19行だけが \n）が混在しているみたいです。

**Comment by matvore** [comment]
@tomoemon さん、ありがとうございます。スクリプトを修正しましたが、動作に影響はないということなので、次リリースに伴ってダウンロード自体が更新されます。

**Comment by matvore** [comment]
このIssueをCloseさせて頂きますが、第３＋第４水準の漢字を入力できない件については、https://github.com/google/horenso/issues/3 と https://github.com/kanchoku/kw/issues/9 を参考に
